# Generated by Django 5.2 on 2025-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor_remove_patient_full_name_patient_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default='+70000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
