# Generated by Django 5.2 on 2025-04-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_service_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicschedule',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialty'),
        ),
    ]
